In [2]:
import numpy as np
M=np.array([[3, 4,5],
            [2,3,4],
            [4,5,6]
           ])
print('M= ',M)

P=np.array([[2,3,4],
           [4,5,6],
           [3,2,4]])
print ('P= ', P)

M=  [[3 4 5]
 [2 3 4]
 [4 5 6]]
P=  [[2 3 4]
 [4 5 6]
 [3 2 4]]


In [3]:
M-P

array([[ 1,  1,  1],
       [-2, -2, -2],
       [ 1,  3,  2]])

In [9]:
np.diag(M)

array([3, 3, 6])

In [6]:
N=np.zeros((3,3))
N

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
Z=np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.dot(M,P)

array([[37, 39, 56],
       [28, 29, 42],
       [46, 49, 70]])

In [9]:
np.dot(P,M)

array([[28, 37, 46],
       [46, 61, 76],
       [29, 38, 47]])

In [10]:
2*M

array([[ 6,  8, 10],
       [ 4,  6,  8],
       [ 8, 10, 12]])

In [12]:
M.transpose()

array([[3, 2, 4],
       [4, 3, 5],
       [5, 4, 6]])

In [14]:
np.linalg.inv(P)

array([[-1.33333333,  0.66666667,  0.33333333],
       [-0.33333333,  0.66666667, -0.66666667],
       [ 1.16666667, -0.83333333,  0.33333333]])

In [15]:
np.mean(M, axis=0)

array([3., 4., 5.])

In [16]:
np.mean(M,axis=1)

array([4., 3., 5.])

In [18]:
np.var(M, axis=0)

array([0.66666667, 0.66666667, 0.66666667])

In [20]:
np.std(M, axis=0)

array([0.81649658, 0.81649658, 0.81649658])

In [21]:
np.var(M,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [22]:
np.std(M, axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [3]:
M*P

array([[ 6, 12, 20],
       [ 8, 15, 24],
       [12, 10, 24]])

In [4]:
M.T

array([[3, 2, 4],
       [4, 3, 5],
       [5, 4, 6]])

In [5]:
np.sum(M, axis=0)

array([ 9, 12, 15])