In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
import pandas as pd


namaFile='DataKaryawan.csv'
data=pd.read_csv(namaFile)
X=data.iloc[:, :-1].values
Y=data.iloc[:,3].values

#print data
print(data)
print("-------------------------")
print("-------------------------")
imp=SimpleImputer(missing_values=np.nan, strategy='mean')
imp=imp.fit(X[:, 1:3])
X[:, 1:3]=imp.transform(X[:, 1:3])
print(X)



        Kota  Usia     Gaji Promosi
0   Salatiga  45.0  66029.0      Ya
1       Solo  34.0  83088.0   Tidak
2     Klaten  38.0  81363.0      Ya
3     Klaten   NaN  93940.0      Ya
4       Solo  42.0  91738.0      Ya
5   Salatiga  29.0  98273.0   Tidak
6       Solo  30.0      NaN   Tidak
7     Klaten  28.0  61111.0      Ya
8     Klaten  34.0  67938.0      Ya
9   Salatiga  39.0  57189.0      Ya
10    Sragen  45.0  45067.0   Tidak
-------------------------
-------------------------
[['Salatiga' 45.0 66029.0]
 ['Solo' 34.0 83088.0]
 ['Klaten' 38.0 81363.0]
 ['Klaten' 36.4 93940.0]
 ['Solo' 42.0 91738.0]
 ['Salatiga' 29.0 98273.0]
 ['Solo' 30.0 74573.6]
 ['Klaten' 28.0 61111.0]
 ['Klaten' 34.0 67938.0]
 ['Salatiga' 39.0 57189.0]
 ['Sragen' 45.0 45067.0]]


In [15]:
#encoder
encoder_X=LabelEncoder()
X[:,0]=encoder_X.fit_transform(X[:,0])
transformer=ColumnTransformer([('Kota', OneHotEncoder(),[0])], remainder='passthrough')
X=np.array(transformer.fit_transform(X), dtype=np.integer)
print(X)

encoder_Y=LabelEncoder()
Y=encoder_Y.fit_transform(Y)
print(Y)

[[    0     1     0     0    45 66029]
 [    0     0     1     0    34 83088]
 [    1     0     0     0    38 81363]
 [    1     0     0     0    36 93940]
 [    0     0     1     0    42 91738]
 [    0     1     0     0    29 98273]
 [    0     0     1     0    30 74573]
 [    1     0     0     0    28 61111]
 [    1     0     0     0    34 67938]
 [    0     1     0     0    39 57189]
 [    0     0     0     1    45 45067]]
[1 0 1 1 1 0 0 1 1 1 0]
