In [5]:
import numpy as np
import statistics
M=np.array([3, 5,7,8,9,9,6,7,8])
M.shape
statistics.median(M)
statistics.mean(M)


6

In [6]:
np.var(M)

3.4320987654320985

In [7]:
np.std(M)

1.852592444503674

In [8]:
A=np.array([[10,14,11,7,9.5,15,19],
           [8,9,17,14.5,12,18,15.5],
           [15,7.5,11.5, 10,10.5, 7, 11],
           [11.5, 11, 9, 12,14,12,7.5]])
A

array([[10. , 14. , 11. ,  7. ,  9.5, 15. , 19. ],
       [ 8. ,  9. , 17. , 14.5, 12. , 18. , 15.5],
       [15. ,  7.5, 11.5, 10. , 10.5,  7. , 11. ],
       [11.5, 11. ,  9. , 12. , 14. , 12. ,  7.5]])

In [9]:
np.percentile(A, 25, axis=None)

9.375

In [15]:
np.percentile(A, 25, axis=0, interpolation="higher")

array([10. ,  9. , 11. , 10. , 10.5, 12. , 11. ])

In [16]:
np.percentile(A, 25, axis=1, interpolation="lower")

array([9.5, 9. , 7.5, 9. ])

In [17]:
np.percentile(A, 75, axis=0, interpolation="lower")

array([11.5, 11. , 11.5, 12. , 12. , 15. , 15.5])

In [18]:
A.mean()

11.75

In [21]:
np.shape(A)

(4, 7)